/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;



public class TesteInterface {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ProjectController projectController
        
//        ProjectController projectController = new ProjectController();
//        Project project = new Project();

        //Insert
//        project.setName("Projeto teste 01");
//        project.setDescription("Descrição teste 01");
//        projectController.save(project);

        //Update
//        project.setId(2);
//        project.setName("Projeto teste 02");
//        project.setDescription("Descrição teste 02");
//        projectController.update(project);

        //List
        //List<Project> projects = projectController.getAll();
        //System.out.println("Total de projetos: " + projects.size());

        //Delete
        //projectController.removeById(3);

//        TaskController taskController = new TaskController();
//        Task task = new Task();

        //Insert
//        task.setIdProject(3);
//        task.setName("Task teste 01");
//        task.setDescription("Task teste 01");
//        task.setNotes("Task teste 01");
//        task.setCompleted(false);
//        taskController.save(task);


//        //Update
//        task.setIdProject(2);
//        task.setId(3);
//        task.setId(3);
//        task.setIdProject(2);
//        task.setDeadline(new Date());
//        task.setName("Task teste 02");
//        taskController.update(task);
//
//        //List
//        List<Task> tasks = taskController.getAll(1);
//        System.out.println("Total de projetos: " + tasks.size());
//
//        //Delete
//        taskController.removeById(1);

    }
}
