/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import main.TesteInterface;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        TesteInterface classUnderTest = new TesteInterface();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
